// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image1":
            case "myImage":return img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`;
            case "image2":
            case "TitleScreen2":return img`
ccccccccccaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaacccccccccc
ccccccccaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaacccccccc
ccccccaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaacccccc
cccccaaaaaaaaaaaaaaaaaeeeeaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaccccc
ccccaaaaaaaaaaaaaaaaeeeaaeeeaaaaaaaaaaaaaaeeeeeecaaaaaaaaeeeaaaaaaaaaaaaaaaaaaaaaaaaaaa.....aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaacccc
cccaaaaaaaaaaaaaaaaeebbbbbaeaaaaaaaaaaaaeeeabbbaecaeeeaaeeaaeaaaaaaaaaaaaaaaaaaaaaaaaaa.....aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaccc
cccaaaaaaaaaaaaaaaaebbbbbbbaeaaaaeeeeaaeebbbbbbbaeeeaeeaeabbecaeeeaaaaaeeeaaaaaaaaaaaaa.....aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaccc
ccaaaaaaaaaaaaaaaaeabbbbbbbbecaaeebbaeaeabbbbabbaeebbbeeebbbeeeeaeeaaaeeaaeaaaaaaaaaaaa.....aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaacc
ccaaaaaaaaaaaaaaaaeabbaeebbbeecceabbbeeeabbeeeaeecebbbaebbbbaeebbaeaaeebbbaeaaaaaaaaaaa.....aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaacc
caaaaaaaaaaaaaaaaaebbbaeeabbecceebbbbaeeabbaeeeecceabbbbbbbbaeebbaeceebbbbbeeaaaaaaaaaa.....aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaac
caaaaaaaaaaaaaaaaeebbbeceebaeceebbbbbbaeebbbeecccceabbbbbabbeeebbaeceabbabbeecaaaaaaaaa.....aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaac
caaaaaaaaaaaaaaaaeabbaeceebaeceabbaebbbeeabbbeeccceabbbbbabbeeebbaeeebbaeaaecccaaaaaaaa.....aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaac
caaaaaaaaaaaaaaaaeabbaeceebaecebbbeeabbeeeabbbaeeceabbbbaabbeeeabaeeabbeeeeccccaaaaaaaa.....aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaac
caaaaaaaaaaaaaaaaeabbaecceaeeeebbaeeabbaeeeabbbaeeeabbeeeabbeceabbeebbaecccccccaaaaaaaa.....aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaac
caaaaaaaaaaaaaaaaeabbaecceeeeeabbeeeebbaeceeabbbaeeabbeeeabbeeeabbeebbaecceeeecaaaaaaaa.....aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaac
caaaaaaaaaaaaaaaaeabbbeccceeeeabbaeeebbbeccceebbbaeabbeceabbaeeabbeebbaeceeabaeaaaaaaaa.....aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaac
caaaaaaaaaaaaaaaaeebbbeeeeabbaebbbeeebbbecccceebbaeabbeceabbaeeabbeebbaeeeabbbeaaaaaaaa.....aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaac
caaaaaaaaaaaaaaaaaebbbaeeabbbeeabbaeabbaeeeeeeabbaeabbeeeebbaeeabbeeabbaabbbbeeccaaaaaa.....aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaac
caaaaaaaaaaaaaaaaaebbbbbbbbbeeeebbbbbbbeeeeaebbbbeeabbaeeebbaeeabbeeebbbbbbaeecccaaaaaa.....aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaac
caaaaaaaaaaaaaaaaaeabbbbbbaeecceebbbbbaeeabbbbbbeeeebbaeeebbaeeebbeeeabbbbaeecccccaaaaa.....aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaac
aaaaaaaaaaaaaaaaaaaeabbeeeeecccceeeaaeeceebbbbaeecceeeeccebbaeceeeeceeeeeeeccccccaaaaaa.....aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
aaaaaaaaaaaaaaaaaaaeebaeeeccccccceeeeeccceeeeeeecccceeccceeeeecceecccceeeccccccccaaaaaa.....aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
aaaaaaaaaaaaaaaaaaaaeaeeccccccccaaccccccccceeccccccccccccceeecccccccccccccccccccaaaaaaa.....aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
aaaaaaaaaaaaaaaaaaaaeeeccccccccaaaacccccccccccccccccaaccccccccccccccccacccccccaaaaaaaaa.....aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
aaaaaaaaaaaaaaaaaaaaaacccccccaaaaaaaacccaaaaccccccaaaaaaaaaaccccaaaaaaaaaaccaaaaaaaaaaa.....aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
aaaaaaaaaaaaaaaaaaaaaaaccccaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.....aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
aaaaaaaaaaaaaaaaaaaaaaaacaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.....aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.....aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.....aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
aaaaaaaaaaaaaaaaaaa.........................................................................aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaeeeeaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaeeeaaeeeaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaeebbbbbaeaaeeeeaaaaaaaaaeeeeeeeeeeaaaeeeaaaaaaeeeaaaeecaaaaaaaaaeaaaeeeeaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaebbbbbbbaeceaaeeaaaaaeeeeeeaaaabaeaaeebaeaaaaeeaeeaeeeeeaaaaaaeeeeeeeabeeeaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaeabbbbbbbbeeebbaeaaaaaeabbbbbbbbbbecaebbbecaaaebbaeeebbaeeeeeaaeabaeebbbbbaeeaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
aaaaaaaaaaaaaaaaaaaaaaaeeaaaaaaaaaaaaaaaaaaaaaeabbaeebbbeeebbaecaaaaebbbbbbbbbbaeceebbbeecacebbbaeebbbeeabeeaebbbeebbbbbbbeeaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
aaaaaaaaaaaaaaaaaaaaaaddeaaaaaaaaaaaaaaaaaaaaaebbbaeeabbeeebbaeccaaaeabbeeeeeeeeeceabbbaecceebbbbeebbbeebbaeaebbbeebbbabbbbecaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
aaaaaaaaaaaaaaaaaaaaadddeaaaaaaaaaaaaaaaaaaaaeebbbeceebaecebbbecccaaeabbeeeeeeeeeceabbbbecceebbbbaebbbeebbaeceabbeebbbeabbbeccaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
aaaeeeaaaaaaaaaaaaaaadddeaaaaaaaaaaaaaaaaaaaaeabbaeceebaecebbbecccaaeebbeeeaabbaecebbabbaeeeebbbbbebbbeabbaeceabbeebbbbbbbaecccadaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
aaeedeeaaaaaaaaaaaaaddddeaaaaaaaaaaaaaaaaaaaaeabbaeceebaecebbbecccaaaebbabbbbbbbeeebbeabbeeeebbbbbabbbeabbaeceabbeebbbbbbeeccccdddddaaaaaaaaaaaaaaaaaaaaaaaaaaaa
aaedddeeaaaaaaaaaaadddddeaaaaaaaaaaaaaaaaaaeeeabbaecceaeecebbbeccceecebbbbbbbbbaeeabbabbbbbbebbabbbbbbeabbaeceabbeeabbbeeecccccddddddaaaaaaaaaaaaaaaaeeeaaaaaaaa
aaddddedaaaaaaaaaaadddddeeaaaaaaaaaaaaaaaaeddeabbaecceeeeeebbbecccddeebbbaeeeeeeeebbbbbbbbbbabbaabbbbbeebbaecebbbeeabbaecccccccdddddddaaaaaaaaaaaaaaaedeeaaaaaaa
aaeddddeaaaaaaaaaaaddddddeeaaaaaaaaaaaaaaaeddeabbbeccceeeeebbbecccddeebbeeeecccceebbbbbbbbaeebbaebbbbaeebbbeeabbaeeabbaeccccccddddddddddaaaaaaaaaaaaaeddeaaaaaaa
aadddddeeaaaaaaaaaddddddddeeaaaaaaaaaaaaaeeddeebbbeeeeabbaebbbeeeeedeebbeeeeeccceabbaeeebbeeebbaeabbbbeeabbeebbbeeeabbaecccccddddddddddddaaaaaaaaaaaaedddeaaaaaa
aaedddddeeaaaaaaaadddddddddeeeaaaaaaaaaaedddddebbbaeeabbbeebbbaaaeeeeabbeeeeeeeeebbaeeeebbaeebbaeebbbbeeebbbabbbeceabbaeccccdddddddddddddaaaaaaaaaaaeedddeeeeaae
deeddddddeaaaaaaaadddddddddddeaaaaaaaaaaedddddebbbbbbbbbeeebbbbbbbbbeabbbbbbbaeeebbeecceabbeebbaeeabbbeeeabbbbbeeceebbaecccdddddddddddddddaaaaaaaaaaedddddddeeee
dddddddddeaaaaaaaadddddddddddeaaaaaaaaaaddddddeabbbbbbaeeceabbbbbbbbeabbbbbbbaeceaaeccceabbeebbeeceabbeceebbbbaecceebbbecccdddddddddddddddaaaaaaaaeedddddddddddd
dddddddddeaaaaaaaadddddddddddeaaaaaaaaaadddddddeabbeeeeecceeeeeeeeeeeeeeeeeeeeccceecccceabbeeeeecceeeeecceeeeeecccceabaecccadddddddddddddddaaaaaaaeddddddddddddd
ddddddddeeaaaaaaaadddddddddddeeaaaaaaaaadddddddeebaeeecccccceeecceeccceeeeeeecccccccccceeaaeccecccceeecccceeeeccccceeeeccccadddddddddddddddaaaaaaaeedddddddddddd
ddddddddeaaaaaaaaaddddddddddddeaaaaaaaaaddddddddeaeeccccccccccccccccccccccccccccccaccccdeeeccccccccccccccccccccccccdeccccccaaddddddddddddddaaaabaaeedddddddddddd
ddddddddeaaaaaaaaaddddddddddddeaaaaaaaaaadddddddeeeccccccccdddcccccccccccccccccccaaaddddddcccccccccddccccdddccccccddeacccccaaddddddddddddddaaaabbaaeeddddddddddd
ddddddeeeaaabbaaaaadddddddddddeaaaaaaaaaadddddddddcccccccdddddddcccccddddccccccaaaaddddddddcccccddddddddddddddccddddeabcccaaaddddddddddddddaaaabbaaaeddddddddddd
ddddddeaaaaaabaaaaadddddddddddeeaaaaaaaaaddddddddddccccdddddddddddddddddddeaaaaaaaadddddddddccddddddddddddddddddddddeabbbaaaaddddddddddddddaaaabbbaaeddddddddddd
ddddddeaaaaaabbaaaaadddddddddddeaaabaaaaadddddddddddcdddddddddddddddddddddeaaaaaaaadddddddddddddddddddddddddddddddddeabbbbaaaadddddddddddddaaabbbbaaeddddddddddd
ddddddeaaaaaaabbaaaadddddddddddeaaabbaaaaaddddddddddddddddddddddddddddddddeaaaaaaaadddddddddddddddddddddddddddddddddeebbbaaaaaddddddddddddaaaabbbbaaeedddddddddd
dddddeeaaaaaaabbaaaaaddddddddddeaaabbaaaaaddddddddddddddddddddddddddddddddeaaaaaaadddddddddddddddddddddddddddddddddddeaaaaaaaaddddddddddddaaabbbbbaaaeeddddddddd
dddddeaaaaaaaabbbaaaadddddddddeeaaabbaaaaadddddddddddddddddddddddddddddddeaaaaaaaadddddddddddddddddddddddddddddddddddeeaaaaaaddddddddddddaaabbbbbbaaaaeddddddddd
ddddeeaaaaaaaabbbbaaadddddddddeaaaabbaaaaaaddddddddddddddddddddddddddddddeaaaaaaaaddddddddddddddddddddddddddddddddddddeeeaaddddddddddddddaaabbbbbbaaaaeddddddddd
ddddeaaaaaaaaaabbbbaaadddddddeeaaaabbaaaaaaddddddddddddddddddddddddddddddeaaaaaaadddddddddddddddddddddddddddddddddddddddddddddddddddddddaaaabbbbbbaaaaeddddddddd
ddddeaaaaaaaaaabbbbbaaddddddeeaaaaabbaaaaaaddddddddddddddddddddddddddddddeaaaaaaaaddddddddddddddddddddddddddddddddddddddddddddddddddddddaaaabbbbbbaaaaeddddddddd
ddddeaaaaaaaaaabbbbbaadddddeeaaaaaaabbaaaaaadddddddddddddddddddddddddddddeaaaaaaaaddddddddddddddddddddddddddddddddddddddddddddddddddddddaaaabbbbbbaaaaeddddddddd
ddddeaaaaaaaaabbbbbbaadddddeeaaaaaaabbbaaaaadddddddddddddddddddddddddddddeaaaaabaaadddddddddddddddddddddddddddddddddddddddddddddddddddddaaaaabbbbbaaaaeddddddddd
ddddeeaaaaaaabbbbbbbaadddddeaaaaaaaabbbbaaaaaddddddddddddddddddddddddddddaaaaaabaaadddddddddddddddddddddddddddddddddddddddddddddddddddddaaaaaabbbaaaaaeddddddddd
dddddeaaaaaaabbbbbbaaadddddeaaaaaaaabbbbaaaaaaddddddddddddddddddddddddddeaaaaabbaaaaddddddddddddddddddddddddddddddddddddddddddddddddddddaaaaaaaaaaaaaeeddddddddd
dddddeeaaaaaaabbbbaaaaddddeeaaaaaaaabbbbaaaaaaddddddddddddddddddddddddddeaaaaabaaaaaaddddddddddddddddddddddddddddddddddddddddddddddddddddaaaaaaaaaaaaedddddddddd
ddddddeaaaaaaaaaaaaaaadddeeaaaaaaaaabbbbbaaaaaddddddddddddddddddddddddddeaaaaabbaaaaaadddddddddddddddddddddddddddddddddddddddddddddddddddaaaaaaaaaaaeedddddddddd
ddddddeeaaaaaaaaaaaaaddddeeaaaaaaaaabbbbbbaaaaadddddddddddddddddddddddddeaaaaabbbaaaaadddddddddddddddddddddddddddddddddddddddddddddddddddddaaaaaaaaadddddddddddd
dddddddeeaaaaaaaaaaaadddeeaaaaaaaaabbbbbbbaaaaadddddddddddddddddddddddddeaaaabbbbaaaaaadddddddddddddddddddddddddddddddddddddddddddddddddddddaaaadddddddddddddddd
ddddddddeeaaaaaaaaaaddddeaaaaaaaaaabbbbbbbaaaaadddddddddddddddddddddddddeaaaabbbbbaaaaaadddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
dddddddddeeeeaaaaaadddddeaaaaaaaaaabbbbbeeeeeaadddddddddddddddddddddddddeaaaabbbbbbaaaaaaddddddddddddddddddddddddceeeddddddddddddddddddddddddddddddddddddddddddd
dddddddddddeedddddddddddeaaaaaaaaaabbbbeabbbbeaadddddddddddddddddddddddeeaaaabbbaaebaaaaadddddddaaeddddddddddddddeabeddddddddddddddddddddddddddddddddddddddddddd
ddddddddddddddddddddddddeaaaaaaaaaabbbbeabeebbeeeeeeeeedeeeeeeeeeeddceeeeeeeeeeebaeeeeeeeeeeeedebaeeeeeedddceeeeeeabeeeeeeeedeeedddddddddddddddddddddddddddddddd
ddddddddddddddddddddddddeaaaaaaaaabbbbbeabeeababbbabbbaebbbbebbbbedeebbbaebbbbaabbbeabbbeabbbeeabbbeabbbeedeabbbbeabeabbbebbeebaeddddddddddddddddddddddddddddddd
ddddddddddddddddddddddddeaaaaaaaaabbbbbeabeebaabaeabeebabeeeabeeeeceabeabebbeabebaeebaebaabeeeeebaeebaebbeceabeebaabeeeebaabeabeeddddddddddddddddddddddddddddddd
ddddddddddddddddddddddddeaaaaaaaabbbbbbeabbbbeabeebbbbbabbaeebbaeecebbbbbabaeabebaeabbbbbabeeeeebaeabeeabeeeabeebbabeabbbaebaabeccdddddddddddddddddddddddddddddd
ddddddddddddddddddddddddeeaaaaaaabbbbbbeabeeeeabeebbeeeeeabbeeabbeeebaeeeebaeabebaeabeeeeabecccebaeabeeabeeeabeebbabebaebaebbbaecccddddddddddddddddddddddddddddd
dddddddddddddddddddddddddeaaaaaaaabbbbbeabeeeeabeeabeeeeeeabeeeabeeeabeeeebaeabebaeebaeeeabecccebaeebaebbeceabeebaababeebaeabbaeccccdddddddddddddddddddddddddddd
dddddddddddddddddddddddddeeaaaaaaabbbbbeabeeceabeeebbbbabbbaebbbaeceebbbbebaeabeabbeabbbaabeccceabbeabbbaeceabbbbeabebbbbaeebbeccccddddddddddddddddddddddddddddd
ddddddddddddddddddddddddddeaaaaaaaaabbbeeeecceeeeceeeeeeeeeeeeeeeecceeeeeeeeeeeeeeeeeeeeeeeeccceeeeeeeeeecceabeeeeeeeeeeeeeebaeccccddddddddddddddddddddddddddddd
ddddddddddddddddddddddddddeeaaaaaaaaaaaaaecccccecccceeeceeecceeecccccceeeceeccecceeccceeceeccccdceecceeeccceabeeccceceeeeeeabaeccccddddddddddddddddddddddddddddd
dddddddddddddddddddddddddddeaaaaaaaaaaaaaaaccccccccccccccccccccccccccccccccccccccccccccccccccccdddccccccccceabeccccccccccebbaeccccdddddddddddddddddddddddddddddd
dddddddddddddddddddddddddddeaaaaaaaaaaaaaaacccdddcccccccccccccccccccdddcccccccccccccccccccccccdddddcccccccceeeecccccccccceeeecccccdddddddddddddddddddddddddddddd
dddddddddddddddddddddddddddeeaaaaaaaaaaaaaaadddddddddddddcccccddccddddddddeeaaaaaaaaaaaaddccddddddddddddccddddcccccddddccccccccccddddddddddddddddddddddddddddddd
ddddddddddddddddddddddddddddeeeeaaaaaaaaaadddddddddddddddddddddddddddddddddeeeaaaaaaaaadddddddddddddddddddddddccccddddddddddcccccddddddddddddddddddddddddddddddd
dddddddddddddddddddddddddddddeeeeaaaaddddddddddddddddddddddddddddddddddddddddeeeedddddddddddddddddddddddddddddddcddddddddddddccddddddddddddddddddddddddddddddddd
dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
edddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddde
edddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddde
edddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddde
edddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddde
edddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddde
edddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddde
edddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddde
edddddddddddddddddddddddddddddddddddddddddddddddddddddeedddeeddddddddddeeedddddddddeeeddddddddddddddeedddeeedeeeeddddddddddddddeeeddddddddddceedddddddddddddddde
edddddddddddddddddddddddddddddddddddddddddddddddddddd877ede778ddddddddde78dddddddd877778ddddddddddd877ede778e7e78edddddddddddde87edddddddde87778edddddddddddddde
edddddddddddddddddddddddddddddddddddddddddddddddddddd877ede778eeeeeddeee78eeeedddd87ee87eeddeeeeddd877ede778eee78eeeeeeeeeeddee87eeeeeddde87eeeeeeeeeeddeeeeeeee
edddddddddddddddddddddddddddddddddddddddddddddddddddd8778e8778e7778ee77778e7778cdd87ee8787ee7787edd8778e877887e78e78e777887ee7787e7777edde78eeee877787ee7877778e
eeddddddddddddddddddddddddddddddddddddddddddddddddddd8777e7778eee87e87e87887e87edd87777e87ee7887edd8777e777887e7878eeee8787ee7887eeee78dde78edde87ee87ee78ee87ee
eeddddddddddddddddddddddddddddddddddddddddddddddddddd8787e7878e7777e78ee7877777edd87ee87e7887eeeedd8787e787887e777eee7777e7887e87e77778dde78edde87ee87ee78ee78ee
eeedddddddddddddddddddddddddddddddddddddddddddddddddd87e787e7877e87e78ee7878eeeedd87ee8788777eeeddd87e787e7887e7778e77e87e8777e8787ee78dde78edde87ee87ee78e77ece
eeedddddddddddddddddddddddddddddddddddddddddddddddddd87e878e7877e87e87e87887eeeedd87ee87ee778eeeedd87e878e7887e7887e77e87ee778e8787e878dde87eeee87ee87ee7887eeee
eeeeddddddddddddddddddddddddddddddddddddddddddddddddd87e878e7887777ee77778e7777edd877778ee77ee87edd87e878e7887e78e7787777ee77ee87e77778ddde7777887eee7777877778e
eeeeeddddddddddddddddddddddddddddddddddddddddddddddddeeeeeeeeeeeeeeeeeeeeeeeeeeeddeeeeeeee77eeeeeddeeeeeeeeeeeeeeeeeeeeeeee77eeeeeeeeeedddeeeeeeeeedeeeeeeeeeeee
eeeeeedddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddeee78cddcddddddddddddddddddddddddeee78cddddddddddddddddddddddddddddeeeeee
eeeeeeeeddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddde877edddddddddddddddddddddddddddde877edddddddddddddddddddddddddddeeeeeeee
eeeeeeeeeeddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddeeeddddddddddddddddddddddddddddddeeeddddddddddddddddddddddddddeeeeeeeeee
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

    helpers._registerFactory("song", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
